---
editor_options:
  markdown:
    wrap: 72
output:
  word_document: default
  html_document: default
  pdf_document: default
---

# HM 878 Applied Biostatistics Problem Set #1c

## Binary Logistic Regression and Cox Proportional Hazards Regression

*This Problem Set will provide students with the opportunity to learn
how to use R to conduct basic statistical tests, replicating many tests
that were already done in HM 802. The main goal is to make sure you are
familiar with R as a system for statistical analysis.*

Analyses include:

-	Binary logistic regression
-	Cox Proportional Hazards Regression


------------------------------------------------------------------------

*Setting up the code environment*

------------------------------------------------------------------------

## Question 1

Data: Logistic Regression Data.csv. Variables: Dependent variable: BMI_Categories.  Independent variables: HLTHPLN1, RFSMOK3, VEGESU1, and SEX.  Variables are coded as follows:
•	BMI_Categories (BMI): 0 = Under/Normal Weight, 1 = Overweight/Obese
•	HLTHPLN1 (Has Health care coverage): 0 = No, 1 = Yes
•	RFSMOK3 (Current Smoker): 0 = No, 1 = Yes
•	VEGESU1 (Servings of vegetables per day): continuous, numerical data
•	SEX (Sex): 0 = Female, 1 = Male


------------------------------------------------------------------------

## Question 2

Run a Cox Regression. Data: Cox Proportional Hazard Regression Data. Variables: Use TimeDeathYears as the “Time” variable. Death is the Status or Event variable.  Use cursmoke, diabetes, educ, prevchd, age, bmi, and sex as the covariates. For the categorical variables, make sure that not a current smoker, no diabetes, the lowest education category, no CHD, and female sex are all reference categories.  Generate 95% CIs for each hazard ratio. Generate a Kaplan Meijer plot.

